### ISSUE TITLE
Linux: AppImages won't work.

### ISSUE THREAD

**Issue by Shockwave508** [dxx-redux/dxx-redux#58]
Steam Deck user here; can't seem to get the AppImages working. Attempting to run through Konsole delivers this error: "error while loading shared libraries: libSDL-1.2.so.0: cannot open shared object file: No such file or directory"

**Comment by jcotton42** [comment]
A bit clunky, but as a workaround you could try running the appimage from a distrobox https://github.com/89luca89/distrobox.

**Comment by arbruijn** [comment]
I have updated the v0.9 AppImages to include the dependencies. Hopefully that makes them work on the Steam Deck. Can you verify?
https://github.com/dxx-redux/dxx-redux/releases/tag/v0.9

**Comment by Shockwave508** [comment]
D1X works perfectly, but D2X somehow cannot "find" itself when ran from the Konsole, and thus fails to boot.

**Comment by Shockwave508** [comment]
UPDATE: Had to allow the AppImage to run at least once in Desktop Mode; it all works now!

**Comment by arbruijn** [comment]
That's good to hear, I'll close the issue.
