### ISSUE TITLE
Rename "Mouse Smoothing" to "Mouse Accumulation"

### ISSUE THREAD

**Issue by KurtLoeffler** [dxx-redux/dxx-redux#84]
The `Mouse Smoothing` options name is misleading IMO. From what I can tell this option accumulates mouse motion into a buffer and takes at most the maximum torque rate each frame from that buffer so that quick flicks can continue to contribute to yaw and pitch over time. This is a very useful option but I bet many players will miss it because the term Mouse Smoothing is generally used to refer to a very different feature in games.

**Comment by SiriusTR** [comment]
Resolved by #103
