### ISSUE TITLE
build issue on Linux ("incompatible pointer type")

### ISSUE THREAD

**Issue by WoolieWool** [dxx-redux/dxx-redux#88]
Attempting to build from the latest source on Arch Linux gives this error message for both the d1 and d2 codebases:

`[ 80%] Building C object main/CMakeFiles/d1x-redux.dir/multibot.c.o
/home/hem/sources/dxx-redux/d1/main/menu.c: In function ‘menu_obs_options_handler’:
/home/hem/sources/dxx-redux/d1/main/menu.c:2370:101: error: passing argument 3 of ‘newmenu_listbox1’ from incompatible pointer type [-Wincompatible-pointer-types]
 2370 |                                 newmenu_listbox1("Select Game Mode", SDL_arraysize(Obs_mode_names), Obs_mode_names,
      |                                                                                                     ^~~~~~~~~~~~~~
      |                                                                                                     |
      |                                                                                                     const char **
In file included from /home/hem/sources/dxx-redux/d1/main/menu.c:48:
/home/hem/sources/dxx-redux/d1/main/newmenu.h:148:65: note: expected ‘char **’ but argument is of type ‘const char **’
  148 | extern listbox *newmenu_listbox1(char *title, int nitems, char *items[], int allow_abort_flag, int default_item, int (*listbox_callback)(listbox *lb, d_event *event, void *userdata), void *userdata);
      |                                                           ~~~~~~^~~~~~~
make[2]: *** [main/CMakeFiles/d1x-redux.dir/build.make:566: main/CMakeFiles/d1x-redux.dir/menu.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:410: main/CMakeFiles/d1x-redux.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Comment by arbruijn** [comment]
This is now fixed in the main branch.
