### ISSUE TITLE
Could not find a valid hog file.

### ISSUE THREAD

**Issue by MelGrubb** [dxx-redux/dxx-redux#95]
I have copied all the files mentioned on the site into the d2x-redux-1.0 directory from my original (and I do mean original, circa 1997 CD ROM), but I'm getting the following dialog when I run.

- - -
Sorry, a critical error has occurred.
- - -
Error: Could not find a valid hog file (descent2.hog or d2demo.hog)
Possible locations are:
	Directory containing D2X-Redux
	~/Library/Preferences/D2X-Rebirth/Data
	In a subdirectory called 'Data'
Or use the -hogdir option to specify an alternate location.
- - -
OK   
- - -

I've put the files in a Data folder; no change. I even copied the entire D2DATA folder from the original CD; no dice. I moved all the items from the ZERO directory to DATA; nope. I've renamed files to be lower case as mentioned in the error, even though Windows is case-insensitive. No joy. What am I missing here?

**Comment by arbruijn** [comment]
If your CD is like mine,  the files in the zero directory are not the right files, these are very small place holders. The correct files on the CD are in the `descent2.sow` file in the D2DATA folder.

The descent2.sow file is actually a arj archive, that you should be able to open with an archive program such as [The Unarchiver](https://apps.apple.com/cz/app/the-unarchiver/id425424353?mt=12). Maybe you need to copy and rename descent2.sow first to `descent2.arj`.

**Comment by MelGrubb** [comment]
Thanks. Maybe future searchers will find this and it'll help.
